apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  volumes:
    - name: my-configuration
      configMap:
        name: configuration-data
  containers:
    - image: "nginx:latest"
      name: example-nginx
      env:
        - name: BACKGROUND_COLOR
          valueFrom:
            configMapKeyRef:
              name: configuration-data
              key: backgroundColor